# Create a new doggy thing with JSON body:
POST http://localhost:3000/article
{
    "id": 0,
    "name": "Frieda",
    "picture": "images/scottish-terrier.jpeg",
    "age": 3,
    "breed": "Scottish Terrier",
    "location": "Lisco, Alabama"
}

POST http://localhost:3000/article
{
  "title": "POV",
  "subHeading": "you are curtis",
  "content": "pov you are curtis >>>>>",
  "headerImage": "https://mixmag.net/assets/uploads/images/_columns2/shrekrave2.png"
}
